pipeline{ 
  agent any
  stages{
    stage("Cleaning Stage") { 
        steps{
		       dir('TestNG'){
			       bat "mvn clean"
		       }
	      }
    }
    stage("Testing Stage") { 
       steps{
		        dir('TestNG'){
				bat "mvn test"
			}
	    }
    }
    stage("Packaging Stage") { 
       steps{
		       dir('TestNG'){
			       bat "mvn package"
		       }
	    }
    }
    stage("Consolidate Results") {
			steps {
				input ("Do you want to capture results?")
				junit '**/target/surefire-reports/TEST-*.xml'
				archive 'TestNG/target/*.jar'
			}
		}
    stage("Email Build Status"){
			steps {
				mail body: "${env.JOB_NAME}  - Build # ${env.BUILD_NUMBER}  - ${currentBuild.currentResult} \n\nCheck console output at ${env.BUILD_URL} to view the results.", subject: "${env.JOB_NAME}  - Build # ${env.BUILD_NUMBER}  - ${currentBuild.currentResult}!!", to: 'awstests2020@gmail.com'
			}
		}	  
  }
}
