pipeline{ 
  agent any
  stages{
    stage("Cleaning Stage") { 
        steps{
		       dir('TestNG'){
			       bat "mvn clean"
		       }
	      }
    }
    stage("Testing Stage") { 
       steps{
		        dir('TestNG'){
				bat "mvn test"
			}
	    }
    }
    stage("Packaging Stage") { 
       steps{
		       dir('TestNG'){
			       bat "mvn package"
		       }
	    }
    }
  }
}
